services:
  db:
    profiles:
      - app
      - migration
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    profiles:
      - migration
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./alembic
        target: /backend/alembic
      - type: bind
        source: ./alembic.ini
        target: /backend/alembic.ini
    environment:
      DB_LINK: postgresql+asyncpg://test:test@db:5432/test
      DB_SCHEMA: xi_auth
    entrypoint: sh

  api:
    profiles:
      - app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - "--reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/backend/app
      - ./tests:/backend/tests
    environment:
      WATCHFILES_FORCE_POLLING: true
      DB_LINK: postgresql+asyncpg://test:test@db:5432/test
      DB_SCHEMA: xi_auth
