services:
  db:
    profiles:
      - app
      - migration
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    profiles:
      - app
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - "--reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/backend/app
      - ./test:/backend/test
    environment:
      WATCHFILES_FORCE_POLLING: true
      DB_LINK: postgresql+psycopg2://test:test@db:5432/test
