name: Preproduction (Create PR)

on:
  push:
    branches:
      - staging

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: staging
          target_branch: main
          title: New Version
          label: "ci:covered,ci:migrated"
          body: |-
            - [ ] version update
            - [ ] migration test
            - [ ] docker image check
